name: it-command
on:
  repository_dispatch:
    types: [it-command]
    
jobs:
  example:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.client_payload.github.payload.repository.full_name }}
      PR_N: ${{ github.event.client_payload.github.payload.issue.number }}
      PR_P: ${{ github.event.issue.number }}
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
          issue-type: pull-request
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ env.PR_N }}/merge'
      - name: Fail Test
        id: action_name_test11
        run: ls
        continue-on-error: true
      - name: Set JAVA_HOME
        run: |
          echo "JAVA_7_HOME=$JAVA_HOME_7_0_312_X64" >> $GITHUB_ENV
          echo "JAVA_8_HOME=$JAVA_HOME_8_X64" >> $GITHUB_ENV
          echo "JAVA_9_HOME=$JAVA_HOME_9_0_7_X64" >> $GITHUB_ENV
          echo "JAVA_HOME=$JAVA_HOME_8_X64" >> $GITHUB_ENV
          echo github.event.number = ${{ env.PR_NUMBER }}
          echo github.event.pull_request.number = ${{ env.PR_N }}
          echo github.event.issue.number = ${{ env.PR_P }}
          echo "$PR_NUMBER"
          echo "$PR_N"
          echo "$PR_P"
          ls
          echo "${{ github.event.client_payload.slash_command.args.all }}"
          echo "=========="
      - name: Dump GitHub pull request context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event.pull_request) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub event context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      - name: Update success comment
        if: steps.action_name_test11.outcome == 'success'
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > :satisfied: [Click here to see the action](${{ steps.vars.outputs.run-url }})
      - name: Update failure comment
        if: steps.action_name_test11.outcome == 'failure'
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > :sob: [Click here to see the action](${{ steps.vars.outputs.run-url }})
